#include "BoardReader.cpp"
//#include "Monitoring.cpp"
#include "NetworkSendData.cpp"
#include "VMETriggerSend.cpp"
#include "CrateReader.cpp"
#include "VMESendData.cpp"
#include "DummyVMETriggerSend.cpp"
//#include "CrateReaderDummy.cpp"
